
server:
  port: 8080

spring:
  datasource:
    username: root
    password: '8324537WoT1997!'
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
    #  show-sql: true
    open-in-view: true
  # logs
  logging:
    level:
      org.hibernate.SQL: info


# example values

indexing-settings:
  sites:
    - url: https://at-store.ru/
      name: at-store
    - url: https://et-cetera.ru/mobile/
      name: et-cetera.ru
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://dombulgakova.ru/
      name: dombulgakova


